scheduler: refactored "last job" helper, defined API confusion
I'll come back to work on this later when I have access to OR-Tool's
forum and can ask more specific questions. Here's a draft of what I
would send, because I'm sure I won't remember by the time I get access
to their forum:

Hello OR-Tools!

I'm using the CpModel/Solver in a personal project where I'm trying to
find an optimal schedule for a number of recipes in a kitchen where
certain steps need certain resources (e.g. "making popcorn requires a
microwave", etc). In particular, I'd like to augment the objective
function to help find solutions where all of the jobs finish near the
same time (so all of your food comes out at the same time :) ). I've
tried to accomplish this with the following code:

'''
recipe_end_diff_var = model.NewIntVar(0, horizon, 'recipe_end_diff')

diffs = []
  for job_a in all_jobs:
    for job_b in all_jobs:
      if job_a != job_b:
        diffs.append(last_task(job_a).end - last_task(job_b).end)

model.AddMaxEquality(recipe_end_diff_var, diffs)
model.Minimize(makespan_var + recipe_end_diff_var)
'''

where "last_task" returns an IntervalVar, and "makespan_var" has already
been defined like in the "Job Shop Problem" example page.

The difficulty is when I'm trying to assign "recipe_end_diff_var" to the
maximum in difference between to IntVars (end time of the last task), as
it seems the API doesn't support it:

'''
TypeError: NotSupported: model.GetOrMakeIndex((end_0_0 + -end_1_0))
'''

So, how should I go about expressing the penalty/preference to the
model? If I can't minimize the difference of two IntVars, maybe I could
enumerate solutions with "SolveWithSolutionObserver" and manually check
afterwards?